#########################################################
# Devices service
#########################################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.devices.name }}
  namespace: {{ .Values.namespace }}
  labels:
    name: {{ .Values.devices.name }}
    app: {{ .Values.app }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.devices.appLabel }}
  replicas: {{ .Values.devices.replicas }}
  template:
    metadata:
      labels:
        app: {{ .Values.devices.appLabel }}
    spec:
      containers:
        - name: {{ .Values.devices.containerName }}
          image: {{ .Values.devices.image }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ .Values.devices.configMapName }}
            - secretRef:
                name: {{ .Values.devices.secretName }}
          env:
            - name: SERVICES
              value: {{ .Values.devices.serviceName }}
          volumeMounts:
            # Mount the ConfigMap as a volume
            - name: config-volume
              mountPath: /etc/config
              readOnly: true
            # Mount the Secret as a volume
            - name: secret-volume
              mountPath: /etc/secret
              readOnly: true
          resources:
            limits:
              cpu: {{ .Values.devices.resources.limits.cpu }}
              memory: {{ .Values.devices.resources.limits.memory }}
            requests:
              cpu: {{ .Values.devices.resources.requests.cpu }}
              memory: {{ .Values.devices.resources.requests.memory }}
        volumes:
        # Define the ConfigMap volume
        - name: config-volume
          configMap:
            name: { { .Values.users.configMapName } }
        # Define the Secret volume
        - name: secret-volume
          secret:
            secretName: { { .Values.users.secretName } }