#########################################################
# GPT service
#########################################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.gpt.name }}
  namespace: {{ .Values.namespace }}
  labels:
    name: {{ .Values.gpt.name }}
    app: {{ .Values.app }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.gpt.appLabel }}
  replicas: {{ .Values.gpt.replicas }}
  template:
    metadata:
      labels:
        app: {{ .Values.gpt.appLabel }}
    spec:
      containers:
        - name: {{ .Values.gpt.containerName }}
          image: {{ .Values.gpt.image }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ .Values.gpt.configMapName }}
            - secretRef:
                name: {{ .Values.gpt.secretName }}
          env:
            - name: SERVICES
              value: {{ .Values.gpt.serviceName }}
          resources:
            limits:
              cpu: {{ .Values.gpt.resources.limits.cpu }}
              memory: {{ .Values.gpt.resources.limits.memory }}
            requests:
              cpu: {{ .Values.gpt.resources.requests.cpu }}
              memory: {{ .Values.gpt.resources.requests.memory }}
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - "wget -qO- http://api:3000/api/v1/gpt/live || exit 1"
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - "wget -qO- http://api:3000/api/v1/gpt/ready || exit 1"
            initialDelaySeconds: 5
            periodSeconds: 10
