apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.monitoring.name }}
  namespace: {{ .Values.namespace }}
  labels:
    name: {{ .Values.monitoring.name }}
    app: {{ .Values.app }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.monitoring.appLabel }}
  replicas: {{ .Values.monitoring.replicas }}
  template:
    metadata:
      labels:
        app: {{ .Values.monitoring.appLabel }}
    spec:
      containers:
        - name: {{ .Values.monitoring.containerName }}
          image: {{ .Values.monitoring.image }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ .Values.monitoring.configMapName }}
            - secretRef:
                name: {{ .Values.monitoring.secretName }}
          env:
            - name: SERVICES
              value: {{ .Values.monitoring.serviceName }}
          resources:
            limits:
              cpu: {{ .Values.monitoring.resources.limits.cpu }}
              memory: {{ .Values.monitoring.resources.limits.memory }}
            requests:
              cpu: {{ .Values.monitoring.resources.requests.cpu }}
              memory: {{ .Values.monitoring.resources.requests.memory }}
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - "wget -qO- http://api:3000/api/v1/monitoring/live || exit 1"
            initialDelaySeconds: 300
            periodSeconds: 600
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - "wget -qO- http://api:3000/api/v1/monitoring/ready || exit 1"
            initialDelaySeconds: 250
            periodSeconds: 600
