namespace: default
app: sistem-za-upravljanje-energije
imagePullPolicy: Always

# API Service
api:
  serviceType: LoadBalancer
  port: 3000
  name: api
  app: api
  serviceName: api
  replicas: 1
  containerName: api
  image: zigac24/sistem-za-upravljanje-energije:latest
  configMapName: molecular-configmap
  secretName: molecular-secrets
  serviceValue: api
  resources:
    limits:
      cpu: 200m
      memory: 500Mi
    requests:
      cpu: 100m
      memory: 40Mi

# Devices Service
devices:
  name: devices-deployment
  appLabel: devices
  serviceName: devices
  replicas: 2
  containerName: devices
  image: zigac24/sistem-za-upravljanje-energije:latest
  configMapName: molecular-configmap
  secretName: molecular-secrets
  serviceValue: devices
  resources:
    limits:
      cpu: 200m
      memory: 500Mi
    requests:
      cpu: 50m
      memory: 40Mi
  livenessProbe:
    path: /devices/live
    initialDelaySeconds: 10
    periodSeconds: 5
  readinessProbe:
    path: /devices/ready
    initialDelaySeconds: 10
    periodSeconds: 10

# GPT Service
gpt:
  name: gpt-deployment
  appLabel: gpt
  serviceName: gpt
  replicas: 2
  containerName: gpt
  image: zigac24/sistem-za-upravljanje-energije:latest
  configMapName: molecular-configmap
  secretName: molecular-secrets
  serviceValue: gpt
  resources:
    limits:
      cpu: 200m
      memory: 500Mi
    requests:
      cpu: 50m
      memory: 40Mi

# NATS Configuration
nats:
  statefulSetName: nats
  configMapName:  nats-config
  serviceName: nats
  appLabel: nats
  replicas: 3
  image: nats:2.1.7-alpine3.11
  httpPort: 8222  # Replace with your desired HTTP port
  clusterPort: 6222  # Replace with your desired cluster port
  clusterRoutes: # Add your cluster routes here if needed
    - "nats://nats-0.nats.default.svc.cluster.local:6222"
    - "nats://nats-1.nats.default.svc.cluster.local:6222"
    - "nats://nats-2.nats.default.svc.cluster.local:6222"
  connectRetries: 30
  leafnodePort: 7422  # Replace with your desired leafnode port
  maxPayload: 4Mb  # Maximum payload size
  terminationGracePeriod: 60
  ports:
    client: 4222
    cluster: 6222
    monitor: 8222
    metrics: 7777
    leafnodes: 7422
    gateways: 7522
  livenessProbe:
    initialDelaySeconds: 30
    timeoutSeconds: 5
  readinessProbe:
    initialDelaySeconds: 30
    timeoutSeconds: 5

# OpenAPI Service
openapi:
  name: openapi-deployment
  appLabel: openapi
  replicas: 2
  containerName: openapi
  image: zigac24/sistem-za-upravljanje-energije:latest
  configMapName: molecular-configmap
  secretName: molecular-secrets
  serviceValue: openapi
  resources:
    limits:
      cpu: 200m
      memory: 500Mi
    requests:
      cpu: 50m
      memory: 40Mi

# Redis Service
redis:
  name: redis
  app: redis
  replicas: 1
  containerName: redis
  image: redis
  port: 6379
  resources:
    limits:
      cpu: 200m
      memory: 500Mi
    requests:
      cpu: 100m
      memory: 40Mi

# Users Service
users:
  name: users-deployment
  appLabel: users
  replicas: 2
  containerName: users
  image: zigac24/sistem-za-upravljanje-energije:latest
  configMapName: molecular-configmap
  secretName: molecular-secrets
  serviceValue: users
  resources:
    limits:
      cpu: 200m
      memory: 500Mi
    requests:
      cpu: 50m
      memory: 40Mi
