namespace: default
app: sistem-za-upravljanje-energije
imagePullPolicy: Always

# API Service
api:
  serviceType: LoadBalancer
  port: 3000
  name: api
  app: api
  serviceName: api
  replicas: 1 # Keep as is for dev
  containerName: api
  image: zigac24/sistem-za-upravljanje-energije:latest # Use a dev image tag
  configMapName: molecular-configmap
  secretName: molecular-secrets
  serviceValue: api
  resources:
    limits:
      cpu: 100m # Lower CPU limit for dev
      memory: 256Mi # Lower memory limit for dev
    requests:
      cpu: 50m # Lower request CPU for dev
      memory: 128Mi # Lower request memory for dev

# Devices Service
devices:
  name: devices-deployment
  appLabel: devices
  serviceName: devices
  replicas: 1 # Reduced for development
  containerName: devices
  image: zigac24/sistem-za-upravljanje-energije:latest # Use a dev image tag
  configMapName: molecular-configmap
  secretName: molecular-secrets
  serviceValue: devices
  resources:
    limits:
      cpu: 100m # Lower CPU limit for dev
      memory: 256Mi # Lower memory limit for dev
    requests:
      cpu: 50m # Lower request CPU for dev
      memory: 128Mi # Lower request memory for dev

# Monitoring Service
monitoring:
  name: monitoring-deployment
  appLabel: monitoring
  serviceName: monitoring
  replicas: 1 # Reduced for development
  containerName: monitoring
  image: zigac24/sistem-za-upravljanje-energije:latest # Use a dev image tag
  configMapName: molecular-configmap
  secretName: molecular-secrets
  serviceValue: monitoring
  resources:
    limits:
      cpu: 100m # Lower CPU limit for dev
      memory: 256Mi # Lower memory limit for dev
    requests:
      cpu: 50m # Lower request CPU for dev
      memory: 128Mi # Lower request memory for dev

# GPT Service
gpt:
  name: gpt-deployment
  appLabel: gpt
  serviceName: gpt
  replicas: 1 # Reduced for development
  containerName: gpt
  image: zigac24/sistem-za-upravljanje-energije:latest # Use a dev image tag
  configMapName: molecular-configmap
  secretName: molecular-secrets
  serviceValue: gpt
  resources:
    limits:
      cpu: 100m # Lower CPU limit for dev
      memory: 256Mi # Lower memory limit for dev
    requests:
      cpu: 50m # Lower request CPU for dev
      memory: 128Mi # Lower request memory for dev

# NATS Configuration
nats:
  statefulSetName: nats
  configMapName: nats-config
  serviceName: nats
  appLabel: nats
  replicas: 1 # Reduced for development
  image: nats:2.1.7-alpine3.11
  httpPort: 8222
  clusterPort: 6222
  clusterRoutes:
    - "nats://nats-0.nats.default.svc.cluster.local:6222"
    - "nats://nats-1.nats.default.svc.cluster.local:6222"
    - "nats://nats-2.nats.default.svc.cluster.local:6222"
  connectRetries: 30
  leafnodePort: 7422
  maxPayload: 4Mb
  terminationGracePeriod: 60
  ports:
    client: 4222
    cluster: 6222
    monitor: 8222
    metrics: 7777
    leafnodes: 7422
    gateways: 7522
  livenessProbe:
    initialDelaySeconds: 30
    timeoutSeconds: 5
  readinessProbe:
    initialDelaySeconds: 30
    timeoutSeconds: 5

# OpenAPI Service
openapi:
  name: openapi-deployment
  appLabel: openapi
  replicas: 1 # Reduced for development
  containerName: openapi
  image: zigac24/sistem-za-upravljanje-energije:latest # Use a dev image tag
  configMapName: molecular-configmap
  secretName: molecular-secrets
  serviceValue: openapi
  resources:
    limits:
      cpu: 100m # Lower CPU limit for dev
      memory: 256Mi # Lower memory limit for dev
    requests:
      cpu: 50m # Lower request CPU for dev
      memory: 128Mi # Lower request memory for dev

# Redis Service
redis:
  name: redis
  app: redis
  replicas: 1 # Keep as is for dev
  containerName: redis
  image: redis
  port: 6379
  resources:
    limits:
      cpu: 100m # Lower CPU limit for dev
      memory: 256Mi # Lower memory limit for dev
    requests:
      cpu: 50m # Lower request CPU for dev
      memory: 128Mi # Lower request memory for dev

# Users Service
users:
  name: users-deployment
  appLabel: users
  replicas: 1 # Reduced for development
  containerName: users
  image: zigac24/sistem-za-upravljanje-energije:latest # Use a dev image tag
  configMapName: molecular-configmap
  secretName: molecular-secrets
  serviceValue: users
  resources:
    limits:
      cpu: 100m # Lower CPU limit for dev
      memory: 256Mi # Lower memory limit for dev
    requests:
      cpu: 50m # Lower request CPU for dev
      memory: 128Mi # Lower request memory for dev
