name: CI/CD Pipeline to Deploy to DigitalOcean Kubernetes

on:
  push:
    branches:
      - main # Trigger the pipeline on pushes to the main branch

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      # Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # Install Docker Compose
      - name: Install Docker Compose
        run: |
          sudo curl -L https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      # Cache Docker layers to speed up builds
      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      # Create .env file
      - name: Create .env file
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_PORT: ${{ secrets.PORT }}
          envkey_API_VERSION: ${{ secrets.API_VERSION }}
          envkey_API_KEY: ${{ secrets.API_KEY }}
          envkey_DB_HOST: ${{ secrets.DB_HOST }}
          envkey_DB_PORT: ${{ secrets.DB_PORT }}
          envkey_DB_NAME: ${{ secrets.DB_NAME }}
          envkey_DB_USER: ${{ secrets.DB_USER }}
          envkey_DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          envkey_POSTGRES_URI: ${{ secrets.POSTGRES_URI }}
          envkey_JWT_SECRET: ${{ secrets.JWT_SECRET }}
          envkey_IOT_HUB_CONNECTION_STRING: ${{ secrets.IOT_HUB_CONNECTION_STRING }}
          directory: backend
          file_name: .env
          fail_on_empty: false
          sort_keys: false

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Run Docker Compose to build and push the images
      - name: Build and push Docker images with npm scripts
        run: |
          cd backend
          npm install
          npm run dc:down
          npm run dc:up
          npm run dc:push

      # Set up kubectl
      - name: Set up kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: "v1.30.5"

      # Authenticate to DigitalOcean Kubernetes
      - name: Authenticate to DigitalOcean Kubernetes
        run: |
          doctl auth init -t ${{ secrets.DIGITALOCEAN_API_TOKEN }}
          doctl kubernetes cluster kubeconfig save ${{ secrets.DIGITALOCEAN_K8S_CLUSTER_NAME }}
